name: sarahbrunscreative
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8521987551357597
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#02b675'
    - '#fefffe'
    - '#252525'
    - '#eea10c'
    - '#e6001c'
  brandStrength: 0.0857740759383887
  lightness: 0.6613085067365319
  saturation: 0.2744785649701953
  rhythmicContrast: 0.967955012107268
purpose: []
